#!/bin/sh -e

./configure \
    --prefix=/usr/gnu \
    --build=x86_64-pc-linux-musl \
    --host=x86_64-pc-linux-musl \
    --enable-targets=x86_64-pep \
    --disable-multilib \
    --disable-werror \
    --with-mmap \
    --with-system-zlib

make all-gas
make DESTDIR="$1" install-gas
