#!/bin/sh -e

# Make sure the Makefile respects the $(MAKE) variable.
# shellcheck disable=SC2016
sed -i 's/\<make\>/$(MAKE)/' libcap/Makefile tests/Makefile

mk() {
    gmake \
        CC="${CC:-cc}" \
        GOLANG=no \
        PREFIX=/usr \
        exec_prefix=/usr \
        LIBDIR=/usr/lib \
        PKGCONFIGDIR=/usr/lib/pkgconfig \
        RAISE_SETFCAP=no \
        "$@"
}

mk
mk DESTDIR="$1" install
