#!/bin/sh -e

cc certdata2pem.c -o mozilla/certdata2pem
sed -i mozilla/Makefile \
    -e 's,python certdata2pem.py,./certdata2pem,g'

make

mkdir -p "$1/usr/share/ca-certificates"
mkdir -p "$1/usr/sbin"
mkdir -p "$1/etc/ssl/certs"

make DESTDIR="$1" PREFIX="$1" install

install -Dm644 sbin/update-ca-certificates.8 \
    "$1/usr/share/man/man8/update-ca-certificates.8"
(
    cd "$1/usr/share/ca-certificates"
    find . -name '*.crt' | sort | cut -b3- > "$1/etc/ca-certificates.conf"
)

mv "$1/usr/sbin" "$1/usr/bin"

ln -s /etc/ssl/certs/ca-certificates.crt "$1/etc/ssl/cert.pem"
