From bmake(1):
> Makefiles should be written so that the mode of bmake operation does
> not change their behavior. For example, any command which needs to use
> "cd" or "chdir" without potentially changing the directory for
> subsequent commands should be put in parentheses so it executes in a
> subshell.

Since bmake doesn't revert its $PWD to the root directory after cd-ing
to a subdir, spawn a subshell.

---
diff --git a/Makefile.in b/Makefile.in
index 705f2a5..1c098b5 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -30,32 +30,32 @@ RM = rm -f
 SHELL = /bin/sh
 
 all : force
-	cd @subdir@; $(MAKE) all
+	(cd @subdir@; $(MAKE) all)
 
 install : force
-	cd @subdir@; $(MAKE) install
+	(cd @subdir@; $(MAKE) install)
 
 installdirs : force
-	cd @subdir@; $(MAKE) installdirs
+	(cd @subdir@; $(MAKE) installdirs)
 
 uninstall : force
-	cd @subdir@; $(MAKE) uninstall
+	(cd @subdir@; $(MAKE) uninstall)
 
 check : force
-	cd @subdir@; $(MAKE) check
+	(cd @subdir@; $(MAKE) check)
 
 mostlyclean : force
-	cd @subdir@; $(MAKE) mostlyclean
+	(cd @subdir@; $(MAKE) mostlyclean)
 
 clean : force
-	cd @subdir@; $(MAKE) clean
+	(cd @subdir@; $(MAKE) clean)
 
 distclean : force
-	cd @subdir@; if test -f Makefile; then $(MAKE) distclean; fi
+	(cd @subdir@; if test -f Makefile; then $(MAKE) distclean; fi)
 	$(RM) config.status config.log config.cache Makefile
 
 maintainer-clean : force
-	cd @subdir@; if test -f Makefile; then $(MAKE) maintainer-clean; fi
+	(cd @subdir@; if test -f Makefile; then $(MAKE) maintainer-clean; fi)
 	$(RM) config.status config.log config.cache Makefile
 
 # List of source files.
